project:
  type: website
  output-dir: docs

website:
  description: "a space for thoughts on psychology, love, relationships, and life."
  site-url: https://claudiadoerrler.github.io/Dias-Blog/
  title: "Dia´s blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
  page-footer:
    center: |
      © 2026 Dia. This work is licensed under 
      [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)
      
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css

  


